myProject/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField , TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):

    title = StringField('Title',validators=[DataRequired()])
    text = TextAreaField('Description',validators=[DataRequired()])
    submit = SubmitField('Post')

myProject/blog_posts/views.py
from flask import render_template, redirect, url_for, Blueprint, abort, request
from myProject.blog_posts.forms import BlogPostForm
from myProject.models import Post
from myProject import db
from flask_login import login_required, current_user

blog_posts = Blueprint('blog_posts',__name__)

@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create():

    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post = Post(title=form.title.data,
                         text = form.text.data,
                         user_id=current_user.id)

        db.session.add(blog_post)
        db.session.commit()

        return redirect(url_for('core.index'))
    
    return render_template('create_post.html',form=form)

@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = Post.query.get_or_404(blog_post_id)

    return render_template('blog_post.html',blog_post=blog_post)

@blog_posts.route('/<int:blog_post_id>/update',methods=['GET','POST'])
@login_required
def update(blog_post_id):
    blog_post = Post.query.get_or_404(blog_post_id)
    
    if blog_post.user != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data

        db.session.commit()

        return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post.id))
    
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template('create_post.html',title='Updating',form=form)

@blog_posts.route('/<int:blog_post_id>/delete',methods=['GET','POST'])
@login_required
def delete(blog_post_id):

    blog_post = Post.query.get_or_404(blog_post_id)

    if blog_post.user != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()

    return redirect(url_for('core.index'))

myProject/core/views.py
from flask import render_template,Blueprint, request
from myProject.models import Post
from flask_login import current_user

core = Blueprint('core',__name__)

@core.route('/')
def index():
    page = request.args.get('page',1,type=int)
    posts = Post.query.order_by(Post.date.desc()).paginate(page=page,per_page=6)
    return render_template('home.html',posts=posts)

@core.route('/blog')
def blog():
    page = request.args.get('page',1,type=int)
    posts = Post.query.order_by(Post.date.desc()).paginate(page=page,per_page=5)
    return render_template('blog.html',posts=posts)

myProject/users/views.py
from flask import redirect,url_for,render_template,request,Blueprint
from myProject.models import User,Post
from myProject.users.forms import LoginForm,RegisterationForm, UpdateUserForm
from myProject import db
from flask_login import login_user, logout_user, login_required, current_user

from myProject.users.picture_handler import add_profile_pic

user = Blueprint('user',__name__)

@user.route('/register',methods=['GET','POST'])
def register():

    form = RegisterationForm()

    if form.validate_on_submit():
        user = User(username=form.username.data,
                    email=form.email.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        return redirect(url_for('user.login'))
    return render_template('register.html',form=form)

@user.route('/login',methods=['GET','POST'])
def login():

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user is not None and user.check_password(form.password.data):
            login_user(user)

            next = request.args.get('next')
            if next == None or not next[0] == '/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)

@user.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('core.index'))
            
# Update User

@user.route('/account',methods=['GET','POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():
        
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()

        return redirect(url_for('user.account'))

    elif request.method == 'GET':

        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static',filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html',profile_image=profile_image,form=form)

@user.route('/<username>')
def blog_post(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = Post.query.filter_by(user=user).order_by(Post.date.desc()).paginate(page=page,per_page=5)
    profile_image = url_for('static',filename='profile_pics/'+current_user.profile_image)
    return render_template('user_blog_posts.html',blog_posts=blog_posts,user=user,profile_image=profile_image)

myProject/templates/account.html
{% extends "base.html" %}

{% block content %}
<div class="my-container p-3 my-4">
<h1 class="text-center">Welcome to page for {{current_user.username}}</h1>
<img alt="" src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}" class='d-block mx-auto my-4'>

<form method='POST' action='' enctype="multipart/form-data">
    {{form.hidden_tag()}}
    <div class='mb-3'>
        {{form.username.label(class='form-label')}}
        {{form.username(class='form-control')}}
    </div>
    <div class='mb-3'>
        {{form.email.label(class='form-label')}}
        {{form.email(class='form-control')}}
    </div>
    <div class='mb-3'>
        {{form.picture.label(class='form-label')}}
        {{form.picture(class='form-control')}}
    </div>
    {{form.submit(class='btn btn-primary')}}
</form>
</div>
{% endblock %}
</div>

myProject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>Document</title>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Mouse+Memoirs&family=Roboto+Slab&display=swap');
      *{
        margin: 0;
        padding: 0;
      }
      .my-container{
          margin: auto;
          margin-top: 50px;
          width: 70vw;
          background-color: beige;
          padding-top: 15px;
          padding-bottom: 22px;
          border-radius: 8px;
           
      }

      .navbar{
        padding: 20px;
        display: flex;
        justify-content: space-between;
        align-items: center;
        background-color: bisque;
      }

      .navbar-items{
        flex-grow: 1;
        display: flex;
        justify-content: space-between;
      }

      .navbar ul{
        display: flex;
        list-style: none;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
        margin-right: 5px;
        /* margin-top: 4px; */
        font-size: 17px;
        margin-bottom: 5px;        
      }

      .navbar ul li{
        margin: 7px;
        margin-bottom: 0;
      }

      .logo{
        margin-left: 10px;
        font-size: 30px;
        font-family: 'Mouse Memoirs', sans-serif;
      }

      li a{
        color: black;
        text-decoration: none;
      }

      .icon{
        color: black;
        font-size: 22px;
        display: none;
      }

      .header{
        padding-top: 170px;
        padding-bottom: 170px;
        display: flex;
        justify-content: space-evenly;
        background-color: beige;
      }

      .header img{
        width: 430px;
      }

      .header h1{
        text-align: center;
        font-size: 55px;
        margin-bottom: 22px;
        font-family: Georgia, 'Times New Roman', Times, serif;
      }

      .lines{
        font-family: Verdana, Geneva, Tahoma, sans-serif;
        width: fit-content;
        margin: auto;
        font-size: 20px;
      }

      .header p{  
        margin: 2px;
      }

      .lines button{
        margin-top: 30px;
        padding: 5px;
        font-size: 18px;
        border: 2px solid black;
        border-radius: 5px;
        background-color: black;
        color: white;
        margin-left: 5px;
      }

      .posts{
        display: flex;
        flex-wrap: wrap;
        justify-content: space-evenly;
      }

      .top-posts{
        background-color: bisque;
        padding: 30px;
        padding-top: 100px;
        padding-bottom: 100px;
      }

      .top-posts h1{
        text-align: center;
        font-size: 40px;
        font-family: 'Roboto Slab', serif;
        margin-bottom: 50px;
      }

      .post{
        width: 28%;
        background-color: aliceblue;
      }

      .post li{
        background: none;
      }

      @media (max-width:1224px) {
        .my-container{
          margin: auto;
          margin-top: 50px;
          width: 90%;
        }
        .header{
          padding-top: 160px;
          padding-bottom: 160px;
        }

        .lines{
          font-size: 18px;
        }

        .header p{
          display: inline;
        }

        .header a{
          display: block;
        }

        .lines button{
          margin-top: 20px;
        }

        .header img{
          width: 400px;
        }

        .top-posts{
          padding-top: 90px;
          padding-bottom: 90px;
        }
      }

      @media (min-width:655px) {
        
        #links{
          display: flex;
        }
      }

      @media (max-width:960px) {
        .header{
          padding-top: 150px;
          padding-bottom: 150px;
        }

        .header h1{
          font-size: 40px;
        }

        .lines{
          font-size: 16px;
        }

        .lines button{
          font-size: 16px;
        }

        .header img{
          width: 330px;
        }

        .post{
          width: 44%;
        }
      }

      @media (max-width:740px) {
        .header{
          padding-top: 130px;
          padding-bottom: 130px;
        }

        .header h1{
          font-size: 30px;
        }
      }

      @media (max-width:656px) {
        .header{
          padding-top: 100px;
          padding-bottom: 90px;
        }

        .top-posts{
          padding-top: 75px;
          padding-bottom: 75px;
        }

        .post{
          width: 100%;
        }

        .header img{
          display: none;
        }

        .lines{
          text-align: center;
        }

        #links{
          /* transition: display 300ms linear; */
          display: none;
          flex-direction: column;
        }

        .navbar-items{
          flex-direction: column;
        }

        .navbar{
          align-items: flex-start;
        }

        .navbar ul{
          padding-left: 5px;
        }

        .icon{
          display: unset;
        }
      }
    </style>
</head>

<body>    
    <nav class="navbar">
      <div class="navbar-items">
        <span class="logo">
          Readers Point
        </span>
        <ul id="links">
          <li><a href="{{url_for('core.index')}}">Home</a></li>
          <li><a href="{{url_for('core.blog')}}">Blog</a></li>
          <li><a href="{{url_for('blog_posts.create')}}">Write</a></li>
          {% if current_user.is_authenticated %}
          <li><a href="{{url_for('user.account')}}">My Account</a></li>
          <li><a href="{{url_for('user.blog_post',username=current_user.username)}}">My Posts</a></li>
          <li><a href="{{url_for('user.logout')}}">Logout</a></li>
          {% else %}
          <li><a href="{{url_for('user.register')}}">Register</a></li>
          <li><a href="{{url_for('user.login')}}">Login</a></li>
          {% endif %}       
        </ul>
      </div>
      <a href="javascript:void(0);" class="icon" onclick="myFunction()">
        <i class="fa fa-bars"></i>
      </a>
    </nav>
    <script>
      function myFunction() {
        var x = document.getElementById("links");
        if (x.style.display === "flex") {
          x.style.display = "none";
        } else {
          x.style.display = "flex";
        }
      }
    </script>
    {% block content %}
    
    {% endblock %}
    
</body>
</html>

myProject/templates/blog.html
{% extends "base.html" %}

{% block content %}

<div class="my-container my-5 px-0 pb-2">

    <div class='m-3'>
        {% for post in posts.items %}
        <div class="card my-2">
            <div class="card-body">
              <h5 class="card-title" ><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h5>
              <p class="card-text">{{post.text[0:250]}}</p>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Written By: {{post.user.username}}</li>
                <li class="list-group-item">Published On: {{post.date.strftime('%Y-%m-%d')}}</li>
              </ul>                
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <!-- <li class="page-item"><a class="page-link" href="#">Previous</a></li> -->
      {% for page_num in posts.iter_pages(left_edge=2,right_edge=2,left_current=2,right_current=2) %}
      {% if page_num %}     
        {% if posts.page == page_num %}
        <li class="page-item disabled">
            <a class="page-link" href="{{url_for('core.blog',page=page_num)}}">{{page_num}}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="{{url_for('core.blog',page=page_num)}}">{{page_num}}</a>
        </li>
        {% endif %}
      {% else %}
      <li class="page-item">
        <a class="page-link text-dark" href="#">...</a>
      </li>
      {% endif %}  
      {% endfor %}
      <!-- <li class="page-item"><a class="page-link" href="#">Next</a></li> -->
    </ul>
</nav>

{% endblock %}

myProject/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="my-container p-3 my-4">
<div class="card">
    <div class="card-body">
      <h2 class="card-title">{{blog_post.title}}</h1>
      <p class="card-text">{{blog_post.text}}</p>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Written By: {{blog_post.username}}</li>
        <li class="list-group-item">Published On: {{blog_post.date.strftime('%Y-%m-%d')}}</li>
      </ul>
      {% if current_user.is_authenticated %}
      <a href="{{url_for('blog_posts.update',blog_post_id=blog_post.id)}}" class="card-link btn btn-primary">Update</a>
      <button type="button" class="card-link btn btn-primary" data-bs-toggle='modal' data-bs-target='#exampleModal'>Delete</button>
      {% endif %}

      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Delete Post</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Are You Sure You Want To Delete This Post?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <form action="{{url_for('blog_posts.delete',blog_post_id=blog_post.id)}}" method="POST">
                  <input type="submit" class="btn btn-primary" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>
         
    </div>
</div>
</div>
{% endblock %}

myProject/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<style>
.write-post{
    display: block;
    width: 100%;
    padding-left: 1px;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #212529;
    padding: 5px;
    background: none;
    border: 1px solid black;
}

.write-post:focus{
    padding: 5px;
    background: none;
    border: 1px solid black;
}
.text-area{
    resize: none;
    border: 1px solid black;
}
</style>
<div class="my-container p-3 my-4">
<form method="POST">
    {{form.hidden_tag()}}
    <div class="mb-3">
        {{form.title.label(class='form-label')}}
        {{form.title(class='write-post')}}
    </div>
    <div class="mb-3">
        {{form.text.label(class='form-label')}}
        {{form.text(class='write-post text-area',style="height:253px")}}
    </div>
    {{form.submit(class='btn btn-primary',style="width:100px;")}}
</form>
</div>

<script>
    const textarea = document.querySelector('.text-area');
    document.addEventListener('keydown',(e)=>{
        const lines = textarea.value.split(/\r\n|\r|\n/).length;
        if(lines>=10){
            if(e.keyCode === 13 && lines<20){
                textarea.style.height = `${24.3*(lines+1)+10}px`;
            }
            else if(e.keyCode === 8 || e.keyCode === 46 && lines>0){
                textarea.style.height = `${24.3*(lines)+10}px`;
            }
        }
    })
    
</script>
{% endblock %}

myProject/templates/home.html
{% extends "base.html" %}

{% block content %}

<section class="header">
  <div>
    <h1>STAY CURIOUS.</h1>
    <div class="lines mx-4">
      <p>Discover stories, thinking, and expertise from writers on any topic.</p>
      <p>Share your thoughts with the world.</p>
      <a href="{{url_for('core.blog')}}"><button>Start Reading</button></a>
    </div>
  </div>
  <img src="https://cdn.pixabay.com/photo/2014/03/24/17/21/newspaper-295480_960_720.png" class="mx-4" alt="">
</section>

<section class="top-posts">
  <h1>Top Posts</h1>
  <div class="posts">
    {% for post in posts.items[:6] %}
    <div class="card my-2 mx-3 post">
        <div class="card-body">
          <h5 class="card-title text-center">{{post.title}}</h5>
          <p class="card-text mx-2">{{post.text[0:100]}}...</p>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Written By: {{post.user.username}}</li>
            <li class="list-group-item">Published On: {{post.date.strftime('%Y-%m-%d')}}</li>
            <li class="list-group-item"><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}"><button class="btn btn-primary">Read More</button></a></li>
          </ul>                
        </div>
    </div>
    {% endfor %}
  </div>
</section>

{% endblock %}

myProject/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="my-container p-3">
<h3 class="mb-3">Login</h3>
<form method='POST'>
    {{form.hidden_tag()}}
    <div class='mb-3'>
        {{form.email.label(class='form-label')}}
        {{form.email(class='form-control')}}
    </div>
    <div class='mb-3'>
        {{form.password.label(class='form-label')}}
        {{form.password(class='form-control')}}
    </div>
    {{form.submit(class='btn btn-primary',style="vertical-align:unset;")}}
    <a href="/register" class="mx-2">Create an account</a>
</form>
</div>
{% endblock %}

myProject/templates/register.html
{% extends "base.html" %}


{% block content %}
<style>
.login{
    margin-top: 5px;
}
</style>
<div class="my-container p-3">
<form method='POST'>
    {{form.hidden_tag()}}
    <div class="mb-3">
        {{form.email.label(class='form-label')}}
        {{form.email(class='form-control')}}
    </div>
    <div class='mb-3'>
        {{form.username.label(class='form-label')}}
        {{form.username(class='form-control')}}
    </div>
    <div class='mb-3'>
        {{form.password.label(class='form-label')}}
        {{form.password(class='form-control')}}
    </div>
    <div class='mb-3'>
        {{form.pass_confirm.label(class='form-label')}}
        {{form.pass_confirm(class='form-control')}}
    </div>
    {{form.submit(class='btn btn-primary',style="vertical-align:unset;")}}
    <a href="/login" class="mx-2">Already a User</a>
</form>
</div>
{% endblock %}

myProject/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="my-container p-3 my-4">
<div class="my-3">
    <h1 class="text-center">Welcome {{user.username}}</h1>
    <img src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}" alt="" class='d-block mx-auto my-4'>
</div>

{% for post in blog_posts.items %}
<div class="card mb-2">
    <div class="card-body">
      <h5 class="card-title" ><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h5>
      <p class="card-text">{{post.text[0:450]}}</p>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Written By: {{user.username}}</li>
        <li class="list-group-item">Published On: {{post.date.strftime('%Y-%m-%d')}}</li>
      </ul>
        
    </div>
</div>
{% endfor %}

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center mt-4">
        <!-- <li class="page-item"><a class="page-link" href="#">Previous</a></li> -->
      {% for page_num in blog_posts.iter_pages(left_edge=2,right_edge=2,left_current=2,right_current=2) %}
      {% if page_num %}     
        {% if blog_posts.page == page_num %}
        <li class="page-item disabled">
            <a class="page-link" href="{{url_for('user.blog_post',username=user.username,page=page_num)}}">{{page_num}}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="{{url_for('user.blog_post',username=user.username,page=page_num)}}">{{page_num}}</a>
        </li>
        {% endif %}
      {% else %}
      <li class="page-item">
        <a class="page-link text-dark" href="#">...</a>
      </li>
      {% endif %}  
      {% endfor %}
      <!-- <li class="page-item"><a class="page-link" href="#">Next</a></li> -->
    </ul>
</nav>
{% endblock %}